language: python
python:
  - "2.7"
install:
  - pip install -r requirements.txt
  - pip install -r dev-requirements.txt
script: nosetests --nocapture --with-coverage --cover-package keepaneyeon
after_success:
  coveralls
